##+++==+++==+++==+++==+++==+++==+++==+++##
##   Color Paltte			##
##+++==+++==+++==+++==+++==+++==+++==+++##

# Pulse
include ./themes/pulse.conf

# Osaka Jade
include ./themes/osaka-jade.conf

##+++==+++==+++==+++==+++==+++==+++==+++##
##   Fonts				##
##+++==+++==+++==+++==+++==+++==+++==+++##
font_family      JetBrainsMonoNerdFont
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.2

##+++==+++==+++==+++==+++==+++==+++==+++##
##   Mouse:Cursor			##
##+++==+++==+++==+++==+++==+++==+++==+++##
mouse_hide_wait -3.0
# url_color #0087bd
url_style double
default_pointer_shape arrow

cursor_shape underline
cursor_shape_unfocused underline
cursor_underline_thickness 2.0
cursor_stop_blinking_after 0

scrollback_lines 2500
scrollback_indicator_opacity 0.5

##+++==+++==+++==+++==+++==+++==+++==+++##
##   Terminal bell			##
##+++==+++==+++==+++==+++==+++==+++==+++##
enable_audio_bell no

##+++==+++==+++==+++==+++==+++==+++==+++##
##   General				##
##+++==+++==+++==+++==+++==+++==+++==+++##
background_opacity 0.4
# selection_foreground none
# selection_background none

editor nvim
update_check_interval 0
shell_integration no-cursor

remember_window_size no
scrollbar_handle_opacity 0.3
scrollbar_track_opacity 0

##+++==+++==+++==+++==+++==+++==+++==+++##
##   Layouts				##
##+++==+++==+++==+++==+++==+++==+++==+++##
enabled_layouts tall:bias=50;full_size=1;mirrored=false

##+++==+++==+++==+++==+++==+++==+++==+++##
##   Keybinds				##
##+++==+++==+++==+++==+++==+++==+++==+++##
# opens new window
map ctrl+enter new_window
# opens new window with the currect active directory
map ctrl+alt+enter launch --cwd=current

# clipboard
map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard

# focus neighboring windows
map ctrl+alt+left neighboring_window left
map ctrl+alt+right neighboring_window right
map ctrl+alt+down neighboring_window down
map ctrl+alt+up neighboring_window up

# switch to the previously active window
map ctrl+p nth_window -1

# moves the window into the previously active tab
map ctrl+f3 detach_window tab-prev

# moves the tab into a new OS window
map ctrl+f2 detach_tab
# asks which OS Window to move the tab into
map ctrl+f4 detach_tab ask

# close all other windows in the tab except the active one
map f9 close_other_windows_in_tab


