## Config by Pegasus pulse

[colors]

background = #0e1815
foreground = #c4c7c5
accent = #228B22

black = #0c1212
red = #a54242
green = #228b22
yellow = #de935f
blue = #668ba9
magenta = #9b4d83
cyan = #5c8b85
white = #acacac
altblack = #626464
altred = #cc6666
altgreen = #6eb66e
altyellow = #f0c674
altblue = #81a2be
altmagenta = #b294bb
altcyan = #8abeb7
altwhite = #c5c8c6

background1 = #004535
background2 = #004b37
background3 = #005238
background4 = #005838
background5 = #005e38
