## Config by Pegasus pulse

[global/wm]
margin-bottom = 0
margin-top = 0

include-file = ./colors.ini
include-file = ./modules.ini
include-file = ./styles.ini

[section/base]
monitor = ${env:MONITOR:}

[bar/pulse1]
inherit = section/base
override-redirect = false

fixed-center = true

width = 100%
height = 25pt
radius = 0

offset-x = 0%
offset-y = 0%

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0pt

border-size = 0pt
border-color = #00000000

padding = 0
module-margin-left = 0
module-margin-right = 0
module-margin-top = 0
module-margin-bottom = 0

font-0 = "JetBrainsMono:size=11;2"
font-1 = "Symbols Nerd Font:size=15;2"
font-2 = "Symbols Nerd Font:size=24;5"
font-3 = "Symbols Nerd Font:size=13;2"
font-4 = "unifont:size=11;12"

modules-left = sepL v2ray 1L xworkspaces 2L nowplaying
modules-center = 1M time spaM mpd spaM date 2M
modules-right = 1R cpu 2R memory 3R pulseaudio 4R wired 5R tray sepR

separator =
dim-value = 1.0
enable-ipc = true

[bar/pulse2]
inherit = section/base
override-redirect = false

fixed-center = true

width = 100%
height = 25pt
radius = 0

offset-x = 0%
offset-y = 0%

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0pt

border-size = 0pt
border-color = #00000000

padding = 0
module-margin-left = 0
module-margin-right = 0
module-margin-top = 0
module-margin-bottom = 0

font-0 = "JetBrainsMono:size=11;2"
font-1 = "Symbols Nerd Font:size=15;2"
font-2 = "Symbols Nerd Font:size=24;5"
font-3 = "Symbols Nerd Font:size=13;2"
font-4 = "unifont:size=11;12"

modules-left = sepL 1L xworkspaces 2L
modules-center = 1M spaM time spaM 2M
modules-right = 6R pulseaudio 4R

separator =
dim-value = 1.0
enable-ipc = true


##___________________________##
[settings]
screenchange-reload = true
pseudo-transparency = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
