## Config by Pegasus pulse

[module/sepL]
type = custom/text
label = --
format-background = ${colors.background2}
format-foreground = ${colors.background2}

[module/sepM]
type = custom/text
label = --
format-background = ${colors.background1}
format-foreground = ${colors.background1}

[module/sepR]
type = custom/text
label = --
format-background = ${colors.background5}
format-foreground = ${colors.background5}

##---------------------------------------------##

[module/1L]
type = custom/text
label = "%{T3}%{T-}"
format-background = ${colors.background2}
format-foreground = ${colors.background1}

[module/2L]
type = custom/text
label = "%{T3}%{T-}"
format-background = ${colors.background1}
format-foreground = ${colors.background}

[module/1M]
type = custom/text
label = "%{T3}%{T-}"
format-background = ${colors.background}
format-foreground = ${colors.background1}

[module/2M]
type = custom/text
label = "%{T3}%{T-}"
format-background = ${colors.background}
format-foreground = ${colors.background1}

[module/1R]
type = custom/text
label = "%{T3}%{T-}"
format-background = ${colors.background}
format-foreground = ${colors.background1}

[module/2R]
type = custom/text
label = "%{T3}%{T-}"
format-background = ${colors.background2}
format-foreground = ${colors.background1}

[module/3R]
type = custom/text
label = "%{T3}%{T-}"
format-background = ${colors.background3}
format-foreground = ${colors.background2}

[module/4R]
type = custom/text
label = "%{T3}%{T-}"
format-background = ${colors.background4}
format-foreground = ${colors.background3}

[module/5R]
type = custom/text
label = "%{T3}%{T-}"
format-background = ${colors.background5}
format-foreground = ${colors.background4}
